version: '3'
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "433:433"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: 'none'
      device: '/home/yell-hajj/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: 'none'
      device: '/home/yell-hajj/data/mariadb'

networks:
  inception:
    driver: bridge